language: c

env:
    - SMVERSION=1.6

matrix:
    fast_finish: true
    
before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib 
    - sudo apt-get install lynx
    - sudo apt-get install curl

before_script:
    - SMPATTERN="http:.*sourcemod-.*-linux.*"
    - SMURL="http://www.sourcemod.net/smdrop/$SMVERSION/"
    - SMPACKAGE=`lynx -dump "$SMURL" | egrep -o "$SMPATTERN" | tail -1`
    - wget $SMPACKAGE
    - tar -xzf $(basename "$SMPACKAGE")
    - rm addons/sourcemod/scripting/*.sp
    - rm -R addons/sourcemod/plugins/*
    - cp -Rv scripting/* addons/sourcemod/scripting/
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - chmod +x compile.sh

script: 
    - ./compile.sh

after_script:
    - cd compiled/
    - wget -O pomf.sh https://gist.githubusercontent.com/KittyKatt/5818701/raw/49e9c8b05e0cfcea295a6dcb1f82bfe4320456bd/pomf
    - chmod +x pomf.sh
    - for i in $(ls *.smx); do ./pomf.sh $i; done